#!/bin/bash
# Post-create script for Dev Container

echo ""
echo "==================================="
echo "SAM 3D Objects Dev Container"
echo "==================================="
echo ""
echo "✓ Container setup complete!"
echo ""
echo "Quick Start:"
echo "  1. Activate environment: mamba activate sam3d-objects"
echo "  2. Verify setup: /workspace/scripts/verify-docker-env.sh"
echo "  3. Run demo: python demo.py"
echo ""
echo "Useful commands:"
echo "  - make test    : Test the environment"
echo "  - make shell   : Open a new shell"
echo ""
echo "Documentation:"
echo "  - Docker guide: doc/docker-setup.md"
echo "  - Quick start: doc/quick-start-docker-ja.md"
echo ""
echo "==================================="
echo ""
